version: '2'

services:
  server:
    container_name: iot-minigh 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true
