version: '3.7'

services:
  server:
    container_name: iot-minigh 
    image: minigh

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 80:8080

    devices:
      - "/dev/gpiomem:/dev/gpiomem"

    privileged: true
