version: '3.7'

services:
  server:
    container_name: iot-minigh 
    image: minigh

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 5000:5000

    # ports:
    #   - 80:5000
    # devices:
    #   - "/dev/gpiomem:/dev/gpiomem"
    # privileged: true
